app/controllers/vacancy/__init__.py
from flask import Blueprint

vacancy = Blueprint("vacancy", __name__)

from . import controllers

app/controllers/vacancy/controllers.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user
from wtforms.validators import Optional

from . import vacancy
from app import app, db, login_manager
from app.models.forms import VacancyForm
from app.models.tables import Vaga, Veiculo

@vacancy.route('/cadastro-de-vagas', methods=['GET', 'POST'])
def register_vacancy():
    if current_user.is_authenticated:
        form = VacancyForm()

        if form.is_submitted():
            localizacao_vaga = form.localizacao_vaga.data
            codigo_vaga = form.codigo_vaga.data
            situacao_vaga = form.situacao_vaga.data.lower()

            vaga = Vaga(
                localizacao=localizacao_vaga,
                codigo=codigo_vaga,
                situacao=situacao_vaga
                )

            # Grava no banco de dados
            db.session.add(vaga)
            db.session.commit()

            # Redireciona para lista de veiculos
            return redirect(url_for('vacancy.list_vacancy'))

        return render_template('vacancy/vacancy_register.html', form=form)

    return redirect('pagina-inicial')


@vacancy.route('/lista-de-vagas', methods=['GET'])
def list_vacancy():
    if current_user.is_authenticated:
        vagas = Vaga.query.filter_by(excluido_vaga=False)
        return render_template('vacancy/vacancy_list.html', vagas=vagas)
    return redirect('pagina-inicial')


@vacancy.route('/editar-vaga/<string:id_vaga>', methods=['GET', 'POST'])
def edit_vacancy(id_vaga):
    if current_user.is_authenticated:
        form = VacancyForm()

        print(form.validate_on_submit())
        if form.is_submitted():
            # Obtem cliente cadastrado no banco de dados
            vaga = Vaga.query.filter_by(id_vaga=id_vaga).first()

            # Informações do formulário
            localizacao_vaga = form.localizacao_vaga.data
            codigo_vaga = form.codigo_vaga.data
            situacao_vaga = form.situacao_vaga.data

            # Altera informações para alteração no banco de dados
            vaga.localizacao_vaga = localizacao_vaga
            vaga.codigo_vaga = codigo_vaga
            vaga.situacao_vaga = situacao_vaga.lower()

            if situacao_vaga.lower() == 'livre':
                vaga.veiculo_placa_veiculo = None

            # Grava no banco de dados
            db.session.add(vaga)
            db.session.commit()

            return redirect(url_for('vacancy.list_vacancy'))

        elif not form.id_vaga.data:
            vaga = Vaga.query.filter_by(id_vaga=id_vaga).first()

            # form.id_cliente.choices = Cliente.list_of_clients()
            if vaga:
                form.situacao_vaga.default = vaga.situacao_vaga.capitalize()
                form.process()

            return render_template(
                'vacancy/vacancy_edit.html',
                form=form,
                vaga=vaga
                )

    return redirect('pagina-inicial')


@vacancy.route('/linkar-vaga/<string:id_vaga>', methods=['GET', 'POST'])
def link_vacancy(id_vaga):
    if current_user.is_authenticated:
        form = VacancyForm()

        print(form.validate_on_submit())

        if form.is_submitted():
            # Obtem cliente cadastrado no banco de dados
            vaga = Vaga.query.filter_by(id_vaga=id_vaga).first()

            # Informações do formulário
            codigo_vaga = form.codigo_vaga.data
            veiculo_placa_veiculo = form.veiculo_placa_veiculo.data

            # Altera informações para alteração no banco de dados
            vaga.codigo_vaga = codigo_vaga
            vaga.veiculo_placa_veiculo = veiculo_placa_veiculo

            # Grava no banco de dados
            db.session.add(vaga)
            db.session.commit()

            return redirect(url_for('vacancy.list_vacancy'))
        elif not form.veiculo_placa_veiculo.data:
            vaga = Vaga.query.filter_by(id_vaga=id_vaga).first()

            form.veiculo_placa_veiculo.choices = Veiculo.list_of_vehicles()
            form.veiculo_placa_veiculo.default = vaga.veiculo_placa_veiculo
            form.process()

            return render_template(
                'vacancy/vacancy_link.html',
                form=form,
                vaga=vaga
                )

    return redirect('pagina-inicial')


@vacancy.route('/excluir-vaga/<string:id_vaga>', methods=['GET', 'POST'])
def delete_vacancy(id_vaga):
    if current_user.is_authenticated:
        vaga = Vaga.query.filter_by(id_vaga=id_vaga).first()
        vaga.excluido_vaga = True
        db.session.add(vaga)
        db.session.commit()
        return redirect(url_for('vacancy.list_vacancy'))
    redirect('pagina-inicial')

app/templates/vacancy/vacancy_edit.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10 bg-white">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Editar Vaga</h2>

            <form method="POST">
                {{ form.csrf_token }}
                
                <div class="form-group">
                    <label for="login">Código da Vaga <span style="color: red;">*</span></label>
                    {{ form.codigo_vaga(id="codigo_vaga", class="form-control", placeholder="Digite o código da vaga", value=vaga.codigo_vaga) }}
                </div>

                <div class="form-group">
                    <label for="login">Localização da Vaga <span style="color: red;">*</span></label>
                    {{ form.localizacao_vaga(id="localizacao_vaga", class="form-control", placeholder="Digite a localização da vaga", value=vaga.localizacao_vaga) }}
                </div>

                <div class="form-group">
                    <label for="login">Situação da Vaga <span style="color: red;">*</span></label>
                    {{ form.situacao_vaga(id="situacao_vaga", class="form-control", placeholder="Digite a situação da vaga", value=vaga.situacao_vaga) }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-vagas">Voltar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/vacancy/vacancy_link.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10 bg-white">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Editar Vaga</h2>

            <form method="POST">
                {{ form.csrf_token }}
                
                <div class="form-group">
                    <label for="login">Código da Vaga</label>
                    {{ form.codigo_vaga(id="codigo_vaga", class="form-control", placeholder="Digite o código da vaga", value=vaga.codigo_vaga) }}
                </div>
                
                <div class="form-group">
                    <label for="veiculo_placa_veiculo">Placa do Veículo</label>
                    {{ form.veiculo_placa_veiculo(id="veiculo_placa_veiculo", class="form-control") }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-vagas">Voltar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/vacancy/vacancy_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 col-xs-12 col-sm-10">
        <div class="col-sm-10 col-xs-12">
            <h2 class="mb-3">Lista de Vagas</h2>
            
            <div class="table-responsive">
                <table id="table" class="table table-striped table-bordered">
                    <thead class="thead-default bg-white">
                        <tr>
                            <th>Código da Vaga</th>
                            <th>Localização da Vaga</th>
                            <th>Situação da Vaga</th>
                            <th>Veículo na Vaga</th>
                            <th class="text-center">Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for vaga in vagas %}
                            <tr>
                                <td>{{ vaga.codigo_vaga }}</td>
                                <td>{{ vaga.localizacao_vaga }}</td>
                                <td>{{ vaga.situacao_vaga }}</td>
                                <td>{{ vaga.veiculo_placa_veiculo }}</td>
                                <td class="d-flex justify-content-center">
                                    <!-- <a class="btn btn-primary" href="{{ url_for('vacancy.link_vacancy', id_vaga=vaga.id_vaga) }}">Adicionar Veículo</a> -- !!!!!!VERIFICAR!!!!!! -->
                                    <a class="btn btn-primary" href="{{ url_for('vacancy.edit_vacancy', id_vaga=vaga.id_vaga) }}">Editar</a>
                                    <div class="ml-3"></div>
                                    <button class="btn btn-danger" onclick="excluir('{{ vaga.id_vaga }}')">Excluir</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>

    </div>
    
    <!-- Função para confirmar exclusão -->
    <script>
        function excluir(id_vaga) {
            if (confirm('Deseja excluir a vaga ' + id_vaga + '?')) {
                window.location.href = '/excluir-vaga/' + id_vaga
            }
        }
    </script>

{% endblock %}

app/templates/vacancy/vacancy_register.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Cadastrar Vaga</h2>

            <form method="POST">
                {{ form.csrf_token }}

                <div class="form-group">
                    <label for="codigo_vaga">Código da Vaga <span style="color: red;">*</span></label>
                    {{ form.codigo_vaga(id="codigo_vaga", class="form-control", placeholder="Digite o código da vaga") }}
                </div>

                <div class="form-group">
                    <label for="localizacao_vaga">Localização da Vaga <span style="color: red;">*</span></label>
                    {{ form.localizacao_vaga(id="localizacao_vaga", class="form-control", placeholder="Digite a localização da vaga") }}
                </div>

                <div class="form-group">
                    <label for="situacao_vaga">Situação da Vaga <span style="color: red;">*</span></label>
                    {{ form.situacao_vaga(id="situacao_vaga", class="form-control", placeholder="Digite a situação da vaga") }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-vagas">Voltar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}