app/controllers/monthly_payment/__init__.py
from flask import Blueprint

monthly_payment = Blueprint("monthly_payment", __name__)

from . import controllers

app/controllers/monthly_payment/controllers.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user

from . import monthly_payment
from app import db
from app.models.forms import MonthlyPayment
from app.models.tables import Mensalidade, Cliente

@monthly_payment.route('/cadastro-de-mensalidade', methods=['GET','POST'])
def register_monthly_payment():
    #Guarda de rota, apenas usuário autenticado pode registrar
    if current_user.is_authenticated:
        form = MonthlyPayment()
        
        if form.is_submitted():
            #Obtem informações do formulário de registro
            id_cliente = form.id_cliente.data
            valor = form.valor.data
            data_vencimento = form.data_vencimento.data
            data_pagamento = form.data_pagamento.data
            situacao =  form.situacao.data.lower()

            #Cria objeto Mensalidade
            monthly_payment = Mensalidade(
                    valor=valor,
                    data_vencimento=data_vencimento,
                    data_pagamento=data_pagamento,
                    situacao=situacao,
                    id_cliente=id_cliente
                )

            #Grava no banco de dados
            db.session.add(monthly_payment)
            db.session.commit()

            #Redireciona para lista de usuários
            return redirect(url_for('monthly_payment.list_monthly_payment'))
        
        #carrega combo box com a lista de funcionários
        elif not form.id_cliente.data:
            form.id_cliente.choices = Cliente.list_of_clients_no_monthly()
            form.process()

        return render_template('monthly_payment/monthly_payment_register.html', form=form)
    
    return redirect('pagina-inicial')

@monthly_payment.route('/lista-de-mensalidades', methods=['GET'])
def list_monthly_payment():
    if current_user.is_authenticated:
        monthly_payments = Mensalidade.query.filter_by(excluido_mensalidade = False)
        return render_template('monthly_payment/monthly_payment_list.html', monthly_payments=monthly_payments)

    return redirect('pagina-inicial')

@monthly_payment.route('/editar-mensalidade/<string:id_mensalidade>', methods=['GET','POST'])
def edit_monthly_payment(id_mensalidade):
    if current_user.is_authenticated:
        form = MonthlyPayment()

        if form.is_submitted():
            #Obtem usuário cadastrado no banco de dados
            monthly_payment = Mensalidade.query.filter_by(id_mensalidade=id_mensalidade).first()
            
            #Obtem informações do formulário
            valor = form.valor.data
            data_vencimento = form.data_vencimento.data
            data_pagamento = form.data_pagamento.data
            situacao =  form.situacao.data.lower()

            #Altera informações para alteração no banco de dados
            monthly_payment.valor_mensalidade = valor
            monthly_payment.data_vencimento_mensalidade = data_vencimento
            monthly_payment.data_pagamento_mensalidade = data_pagamento
            monthly_payment.situacao_mensalidade = situacao

            #Grava no banco de dados
            db.session.add(monthly_payment)
            db.session.commit()

            return redirect(url_for('monthly_payment.list_monthly_payment'))
        else:
            monthly_payment = Mensalidade.query.filter_by(id_mensalidade=id_mensalidade).first()

            if monthly_payment: 
                client = Cliente.query.filter_by(id_cliente=monthly_payment.cliente_id_cliente).first()
                
                #carrega campos de seleção
                form.id_cliente.choices = [(client.id_cliente, client.nome_cliente)]
                form.situacao.default = monthly_payment.situacao_mensalidade.capitalize()
                form.process()
            return render_template('monthly_payment/monthly_payment_edit.html', form=form, monthly_payment=monthly_payment)
    
    return redirect('pagina-inicial')

@monthly_payment.route('/excluir-mensalidade/<string:id_mensalidade>', methods=['GET','POST'])
def delete_monthly_payment(id_mensalidade):
    if current_user.is_authenticated:
        monthly_payment = Mensalidade.query.filter_by(id_mensalidade=id_mensalidade).first()
        monthly_payment.excluido_mensalidade = True
        db.session.add(monthly_payment)
        db.session.commit()
        return redirect(url_for('monthly_payment.list_monthly_payment'))

    return redirect('pagina-inicial')

app/templates/monthly_payment/monthly_payment_edit.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Editar Mensalidade</h2>

            <form method="POST">
                {{ form.csrf_token }}

                <div class="form-group">
                    <label for="id_cliente">Id Cliente</label>
                    {{ form.id_cliente(id="id_cliente", class="form-control", disabled=True) }}
                </div>

                <div class="form-group">
                    <label for="id_mensalidade">Id Mensalidade</label>
                    {{ form.id_mensalidade(id="id_mensalidade", class="form-control", value=monthly_payment.id_mensalidade, disabled=True) }}
                </div>

                <div class="form-group">
                    <label for="valor">Valor da Mensalidade</label>
                    {{ form.valor(id="valor", class="form-control", placeholder="Digite o valor da mensalidade", value=monthly_payment.valor_mensalidade) }}
                </div>

                <div class="form-group">
                    <label for="data_vencimento">Data de Vencimento</label>
                    {{ form.data_vencimento(id="data_vencimento", class="form-control", placeholder="XX/XX/XXXX", value=monthly_payment.data_vencimento_mensalidade) }}
                </div>

                <div class="form-group">
                    <label for="data_pagamento">Data do Pagamento</label>
                    {{ form.data_pagamento(id="data_pagamento", class="form-control",placeholder="XX/XX/XXXX", value=monthly_payment.data_pagamento_mensalidade) }}
                </div>

                <div class="form-group">
                    <label for="situacao">Situação</label>
                    {{ form.situacao(id="situacao", class="form-control") }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-mensalidades">Voltar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/monthly_payment/monthly_payment_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 col-xs-12 col-sm-10">
        <div class="col-sm-10 col-xs-12">
            <h2 class="mb-3">Lista de Mensalidades</h2>
            
            <div class="table-responsive">
                <table id="table" class="table table-striped table-bordered">
                    <thead class="thead-default bg-white">
                        <tr>
                            <th>Id mensalidade</th>
                            <th>Id cliente</th>
                            <th>Valor mensalidade</th>
                            <th>Data de vencimento</th>
                            <th>Data de pagamento</th>
                            <th>Situação</th>
                            <th class="text-center">Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for monthly in monthly_payments %}
                            <tr>
                                <td>{{ monthly.id_mensalidade }}</td>
                                <td>{{ monthly.cliente_id_cliente }}</td>
                                <td>{{ monthly.valor_mensalidade }}</td>
                                <td>{{ monthly.data_vencimento_mensalidade }}</td>
                                <td>{{ monthly.data_pagamento_mensalidade }}</td>
                                <td>{{ monthly.situacao_mensalidade.capitalize() }}</td>

                                <td class="d-flex justify-content-center align-bottom">
                                    <a class="btn btn-primary" href="{{ url_for('monthly_payment.edit_monthly_payment', id_mensalidade=monthly.id_mensalidade) }}">Editar</a>
                                    <div class="ml-3"></div>
                                    <button class="btn btn-danger" onclick="excluir('{{ monthly.id_mensalidade }}')">Excluir</button>
                                </td>
                            </tr>
                            {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>

    </div>
    
    <!-- Função para confirmar exclusão -->
    <script>
        function excluir(id_mensalidade) {
            if (confirm('Deseja a mensalidade ' +id_mensalidade+ '?')) {
                window.location.href = '/excluir-mensalidade/' + id_mensalidade
            }
        }
    </script>

{% endblock %}

app/templates/monthly_payment/monthly_payment_register.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Cadastrar Mensalidade</h2>

            <form method="POST">
                {{ form.csrf_token }}

                <div class="form-group">
                    <label for="id_cliente">Cliente</label>
                    {{ form.id_cliente(id="id_cliente", class="form-control") }}
                </div>

                <div class="form-group">
                    <label for="valor">Valor da Mensalidade</label>
                    {{ form.valor(id="valor", class="form-control", placeholder="Digite o valor da mensalidade") }}
                </div>

                <div class="form-group">
                    <label for="data_vencimento">Data de Vencimento</label>
                    {{ form.data_vencimento(id="data_vencimento", class="form-control", placeholder="XX/XX/XXXX") }}
                </div>

                <div class="form-group">
                    <label for="data_pagamento">Data do Pagamento</label>
                    {{ form.data_pagamento(id="data_pagamento", class="form-control", placeholder="XX/XX/XXXX") }}
                </div>

                <div class="form-group">
                    <label for="situacao">Situação</label>
                    {{ form.situacao(id="situacao", class="form-control") }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-mensalidades">Voltar</a>
                </div>
            </form>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#id_cliente').select2();
        });
    </script>
{% endblock %}