app/controllers/damage/__init__.py
from flask import Blueprint

damage = Blueprint("damage", __name__)

from . import controllers

app/controllers/damage/controllers.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user
from wtforms.validators import Optional

from . import damage
from app import app, db, login_manager
from app.models.forms import DamageForm
from app.models.tables import Avaria, Veiculo

@damage.route('/cadastro-de-avarias', methods=['GET', 'POST'])
def register_damage():
    if current_user.is_authenticated:
        form = DamageForm()

        if form.is_submitted():
            descricao_avaria = form.descricao_avaria.data
            observacao_avaria = form.observacao_avaria.data
            placa_veiculo = form.placa_veiculo.data

            avaria = Avaria(
                descricao=descricao_avaria,
                observacao=observacao_avaria,
                placa_veiculo=placa_veiculo
                )

            # Grava no banco de dados
            db.session.add(avaria)
            db.session.commit()

            # Redireciona para lista de veiculos
            return redirect(url_for('damage.list_damage'))

        # carrega combo box com a lista de veiculos
        elif not form.placa_veiculo.data:
            form.placa_veiculo.choices = Veiculo.list_of_vehicles()
            form.process()

        return render_template('damage/damage_register.html', form=form)

    return redirect('pagina-inicial')


@damage.route('/lista-de-avarias', methods=['GET'])
def list_damage():
    if current_user.is_authenticated:
        avarias = Avaria.query.filter_by(excluido_avaria=False)
        return render_template('damage/damage_list.html', avarias=avarias)
    return redirect('pagina-inicial')


@damage.route('/editar-avaria/<string:id_avaria>', methods=['GET', 'POST'])
def edit_damage(id_avaria):
    if current_user.is_authenticated:
        form = DamageForm()

        print(form.validate_on_submit())
        if form.is_submitted():
            # Obtem cliente cadastrado no banco de dados
            avaria = Avaria.query.filter_by(id_avaria=id_avaria).first()

            # Informações do formulário
            descricao_avaria = form.descricao_avaria.data
            observacao_avaria = form.observacao_avaria.data

            # Altera informações para alteração no banco de dados
            avaria.descricao_avaria = descricao_avaria
            avaria.observacao_avaria = observacao_avaria

            # Grava no banco de dados
            db.session.add(avaria)
            db.session.commit()

            return redirect(url_for('damage.list_damage'))

        elif not form.id_avaria.data:
            avaria = Avaria.query.filter_by(id_avaria=id_avaria).first()

            if avaria:
                form.placa_veiculo.choices = Veiculo.list_of_vehicles()
                form.placa_veiculo.default = avaria.placa_veiculo_placa
                form.process()

            return render_template(
                'damage/damage_edit.html',
                form=form,
                avaria=avaria
                )

    return redirect('pagina-inicial')


@damage.route('/excluir-avaria/<string:id_avaria>', methods=['GET', 'POST'])
def delete_damage(id_avaria):
    if current_user.is_authenticated:
        avaria = Avaria.query.filter_by(id_avaria=id_avaria).first()
        avaria.excluido_avaria = True
        db.session.add(avaria)
        db.session.commit()
        return redirect(url_for('damage.list_damage'))
    redirect('pagina-inicial')

app/templates/damage/damage_edit.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Editar Avaria</h2>

            <form method="POST">
                {{ form.csrf_token }}
                <div class="form-group">
                    <label for="placa_veiculo">Placa do Veículo <span style="color: red;">*</span></label>
                    {{ form.placa_veiculo(id="placa_veiculo", class="form-control") }}
                </div>

                <div class="form-group">
                    <label for="descricao_avaria">Descrição da Avaria <span style="color: red;">*</span></label>
                    {{ form.descricao_avaria(id="descricao_avaria", class="form-control", placeholder="Digite a descrição da avaria", value=avaria.descricao_avaria) }}
                </div>

                <div class="form-group">
                    <label for="observacao_avaria">Observação da Avaria</label>
                    {{ form.observacao_avaria(id="observacao_avaria", class="form-control", placeholder="Digite a observação da avaria", value=avaria.observacao_avaria) }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-avarias">Voltar</a>
                </div>
            </form>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#placa_veiculo').select2();
        });
    </script>
{% endblock %}

app/templates/damage/damage_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 col-xs-12 col-sm-10">
        <div class="col-sm-10 col-xs-12">
            <h2 class="mb-3">Lista de Avarias</h2>
            
            <div class="table-responsive">
                <table id="table" class="table table-striped table-bordered">
                    <thead class="thead-default bg-white">
                        <tr>
                            <th>Id</th>
                            <th>Placa Veículo</th>
                            <th>Descrição da Avaria</th>
                            <th>Observação da Avaria</th>
                            <th class="text-center">Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for avaria in avarias %}
                            <tr>
                                <td>{{ avaria.id_avaria }}</td>
                                <td>{{ avaria.placa_veiculo_placa }}</td>
                                <td>{{ avaria.descricao_avaria }}</td>
                                <td>{{ avaria.observacao_avaria }}</td>
                                <td class="d-flex justify-content-center">
                                    <a class="btn btn-primary" href="{{ url_for('damage.edit_damage', id_avaria=avaria.id_avaria) }}">Editar</a>
                                    <div class="ml-3"></div>
                                    <button class="btn btn-danger" onclick="excluir('{{ avaria.id_avaria }}', '{{ avaria.placa_veiculo_placa }}')">Excluir</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>

    </div>
    
    <!-- Função para confirmar exclusão -->
    <script>
        function excluir(id_avaria, placa) {
            if (confirm('Deseja excluir a avaria do veículo ' + placa + '?')) {
                window.location.href = '/excluir-avaria/' + id_avaria
            }
        }
    </script>

{% endblock %}

app/templates/damage/damage_register.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-8 col-xs-12">
            <h2 class="mb-2">Cadastrar Avaria</h2>

            <form method="POST">
                {{ form.csrf_token }}

                <div class="form-group">
                    <label for="placa_veiculo">Placa do Veículo <span style="color: red;">*</span></label>
                    {{ form.placa_veiculo(id="placa_veiculo", class="form-control") }}
                </div>

                <div class="form-group">
                    <label for="descricao_avaria">Descrição da Avaria <span style="color: red;">*</span></label>
                    {{ form.descricao_avaria(id="descricao_avaria", class="form-control", placeholder="Digite a descrição da avaria") }}
                </div>

                <div class="form-group">
                    <label for="observacao_avaria">Observação da Avaria</label>
                    {{ form.observacao_avaria(id="observacao_avaria", class="form-control", placeholder="Digite a situação da avaria") }}
                </div>

                <div class="text-center">
                    <button class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-de-avarias">Voltar</a>
                </div>
            </form>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#placa_veiculo').select2();
        });
    </script>
{% endblock %}