app/controllers/parking/__init__.py
from flask import Blueprint

parking = Blueprint("parking", __name__)

from . import controllers

app/controllers/parking/controllers.py
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user
from wtforms.validators import Optional
import json

from . import parking
from app import db, login_manager
from app.models.forms import Parking, ServiceParking
from app.models.tables import Estacionamento, Veiculo, Cliente, Vaga, Servico, ServicoEstacionamento, UsuarioEstacionamento, and_

@parking.route('/registrar-entrada-estacionamento', methods=['GET', 'POST'])
def register_parking():
    if current_user.is_authenticated:
        form_parking = Parking()
        form_service = ServiceParking()
        qtdVacancy = Vaga.available_vacancies()

        if form_parking.is_submitted():
            placa_veiculo = form_parking.placa_veiculo.data
            id_vaga = form_parking.id_vaga.data
            entrada = form_parking.entrada.data
            saida = form_parking.saida.data
            observacao = form_parking.observacao.data
            valor_total = float(form_parking.valor_total.data)
            valor_liquido = valor_total
            situacao = 'pendente'
            servicos = json.loads(form_parking.servicos.data)

            parking = Estacionamento(
                placa_veiculo=placa_veiculo,
                id_vaga=id_vaga,
                entrada=entrada,
                saida=saida,
                observacao=observacao,
                valor_liquido=valor_liquido,
                valor_total=valor_total,
                situacao=situacao
                )

            # Grava no banco de dados
            db.session.add(parking)
            db.session.commit()
            db.session.refresh(parking)

            user = UsuarioEstacionamento(
                id_estacionamento=parking.id_estacionamento,
                login_usuario=current_user.login_usuario
                )

            db.session.add(user)
            db.session.commit()

            space = db.session\
                    .query(Vaga)\
                    .filter(
                        and_(
                                Vaga.id_vaga == int(id_vaga), 
                                Vaga.excluido_vaga == False,
                                Vaga.veiculo_placa_veiculo == None
                            )\
                        )\
                    .first()
            
            if space:
                space.veiculo_placa_veiculo = placa_veiculo
                space.situacao_vaga = 'ocupada'
                db.session.add(space)
                db.session.commit()
            

            for servico in servicos:
                service = ServicoEstacionamento(
                    id_estacionamento=parking.id_estacionamento,
                    id_servico=servico['id'],
                    nome=servico['nome'],
                    preco=servico['preco']
                )
                db.session.add(service)
                db.session.commit()


            # Redireciona para lista de registros estacionamento
            return redirect(url_for('parking.list_parking', tipo_listagem='entradas'))

        #carrega combo box com a lista de funcionários
        else:
            if not form_parking.placa_veiculo.data:
                form_parking.placa_veiculo.choices = Veiculo.list_of_vehicle_no_parked()
                form_parking.process()
            
            if not form_parking.id_vaga.data:
                form_parking.id_vaga.choices = Vaga.list_of_spaces()
                form_parking.process()

        return render_template('parking/parking_register.html', form_parking=form_parking, form_service=form_service, qtdVacancy=qtdVacancy)

    return redirect('pagina-inicial')

@parking.route('/busca-servico/<string:id_servico>', methods=['GET'])
def search_service(id_servico):
    if id_servico and current_user.is_authenticated:
        service = db.session\
                    .query(Servico)\
                    .filter(
                        and_(
                                Servico.id_servico == int(id_servico), 
                                Servico.situacao_servico == 'ativo',
                                Servico.excluido_servico == False
                            )\
                        )\
                    .first()
        if service:
            registry = {}
            registry['id'] = service.id_servico
            registry['nome'] = service.nome_servico
            registry['descricao'] = service.descricao_servico
            registry['preco'] = service.preco_servico
            registry['tipo'] = service.tipo_servico

            return jsonify(registry), 200
    return jsonify([{'error': 'Código inválido.'}]), 403

@parking.route('/todos-servicos', methods=['GET'])
def all_services():
    # if current_user.is_authenticated:
    services = db.session\
                .query(Servico)\
                .filter(
                    and_(
                            Servico.situacao_servico == 'ativo',
                            Servico.excluido_servico == False
                        )\
                    )
    registry = [
        {
            'id': 0,
            'nome': ""
        }
    ]
    
    for service in services:
        registry.append(
            {
                'id': service.id_servico,
                'nome': service.nome_servico
            }
        )

    return jsonify(registry), 200
    # return jsonify([{'error': 'Código inválido.'}]), 403

@parking.route('/lista-registros-estacionamento/<string:tipo_listagem>', methods=['GET'])
def list_parking(tipo_listagem):
    if current_user.is_authenticated:
        if tipo_listagem == 'entradas':
            parkings = db.session.query(Estacionamento).filter(and_(Estacionamento.saida_estacionamento == None, Estacionamento.excluido_estacionamento == False))
        elif tipo_listagem == 'saidas':
            parkings = db.session.query(Estacionamento).filter(and_(Estacionamento.saida_estacionamento != None, Estacionamento.excluido_estacionamento == False))
        return render_template('parking/parking_list.html', parkings=parkings)
    return redirect('pagina-inicial')


@parking.route('/registro-estacionamento/<string:id_estacionamento>', methods=['GET', 'POST'])
def edit_parking(id_estacionamento):
    if current_user.is_authenticated:
        form_parking = Parking()

        if form_parking.is_submitted():
            placa_veiculo = form_parking.placa_veiculo.data
            id_vaga = form_parking.id_vaga.data
            observacao = form_parking.observacao.data
            valor_total = float(form_parking.valor_total.data)
            servicos = json.loads(form_parking.servicos.data)

            parking = Estacionamento.query.filter_by(id_estacionamento=id_estacionamento).first()
            id_vaga_origem = parking.vaga_id_vaga

            parking.veiculo_placa_veiculo = placa_veiculo
            parking.vaga_id_vaga = id_vaga
            parking.observacao_estacionamento = observacao
            parking.valor_liquido_estacionamento = valor_total
            parking.valor_total_estacionamento = valor_total

            # Grava no banco de dados
            db.session.add(parking)
            db.session.commit()

            space_origin = Vaga.query.filter_by(id_vaga=id_vaga).first()

            space = db.session\
                    .query(Vaga)\
                    .filter(
                        and_(
                                Vaga.id_vaga == int(id_vaga), 
                                Vaga.excluido_vaga == False,
                                Vaga.veiculo_placa_veiculo == None
                            )\
                        )\
                    .first()
            
            if space:
                space.veiculo_placa_veiculo = placa_veiculo
                space.situacao_vaga = 'ocupada'
                db.session.add(space)
                db.session.commit()
            
            if space_origin:
                space_origin.veiculo_placa_veiculo = None
                space_origin.situacao_vaga = 'livre'
                db.session.add(space_origin)
                db.session.commit()

            for servico in servicos:
                service = db.session\
                            .query(ServicoEstacionamento)\
                            .filter(
                                and_(
                                    ServicoEstacionamento.estacionamento_id_estacionamento == id_estacionamento,
                                    ServicoEstacionamento.servico_id_servico == servico['id_origem'],
                                    ServicoEstacionamento.excluido_servico == False
                                )
                            ).first()
                print(service)
                if service:
                    service.servico_id_servico = servico['id']
                    service.nome_servico = servico['nome']
                    service.preco_servico = servico['preco']
                    service.excluido_servico = servico['excluido'] == 'true'
                else:
                    service = ServicoEstacionamento(
                        id_estacionamento=parking.id_estacionamento,
                        id_servico=servico['id'],
                        nome=servico['nome'],
                        preco=servico['preco']
                    )
                db.session.add(service)
                db.session.commit()

            # Redireciona para lista de registros estacionamento
            return redirect(url_for('parking.list_parking', tipo_listagem='entradas'))

        else:
            parking = Estacionamento.query.filter_by(id_estacionamento=id_estacionamento).first()
            services = db.session\
                        .query(
                            Servico.id_servico,
                            ServicoEstacionamento.nome_servico, 
                            Servico.descricao_servico,
                            ServicoEstacionamento.preco_servico,

app/templates/parking/parking_edit.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table-service.css') }}">

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-12 col-xs-12">
            {% set read_obs = False %}

            {% if saida %}
                <h2 class="p-3 mb-3">Registrar Saída</h2>
            {% else %}
                {% if parking.situacao_estacionamento == 'pendente' %}
                <h2 class="p-3 mb-3">Editar Entrada</h2>
                {% else %}
                    <h2 class="p-3 mb-3">Visualização Saída</h2>
                    {% set read_only = True %}
                    {% set read_obs = True %}
                {% endif %}
            {% endif %}

            <form method="POST">
                {{ form_parking.csrf_token }}
                
                <div class="d-flex justify-content-center">
                    <div class="form-group col-4">
                        <label for="placa_veiculo">Placa do Veículo <span style="color: red;">*</span></label>
                        {{ form_parking.placa_veiculo(id="placa_veiculo", class="form-control", placeholder="Digite a placa do veículo", readonly=read_only) }}
                    </div>

                    <div class="form-group col-4">
                        <label for="id_vaga">Vaga <span style="color: red;">*</span></label>
                        {{ form_parking.id_vaga(id="id_vaga", class="form-control", placeholder="Digite a vaga", readonly=read_only) }}
                    </div>

                    <div class="form-group col-4">
                        <label for="observacao">Observação</label>
                        {{ form_parking.observacao(id="observacao", class="form-control", placeholder="Digite uma observação", value=parking.observacao_estacionamento, readonly=read_obs) }}
                    </div>
                </div>
                
                <div class="d-flex justify-content-center">
                    <div class="form-group col-4">
                        <label for="entrada">Data/hora Entrada</label>
                        {{ form_parking.entrada(id="entrada", class="form-control", readonly=True, value=parking.entrada_estacionamento ) }}
                    </div>
                    {% if not saida %}
                        <div class="form-group col-4">
                            <label for="situacao">Situação Pagamento</label>
                            {{ form_parking.situacao(id="situacao", class="form-control", placeholder="", readonly=True, value=parking.situacao_estacionamento.capitalize() ) }}
                        </div>

                        <div class="form-group col-4">
                            <label for="valor_total">Valor Total</label>
                            {{ form_parking.valor_total(id="valor_total", class="form-control", placeholder="", readonly=True, value=parking.valor_total_estacionamento ) }}
                        </div>
                    {% else %}
                        <div class="form-group col-4">
                            <label for="saida">Data/hora Saída</label>
                            {{ form_parking.saida(id="saida", class="form-control", readonly=True ) }}
                        </div>
                        
                        <div class="form-group col-4">
                            <label for="tempo_permanencia">Tempo Permanência</label>
                            {{ form_parking.tempo_permanencia(id="tempo_permanencia", class="form-control", placeholder="", readonly=True) }}
                        </div>

                    {% endif %}
                </div>

                <div class="d-flex justify-content-center">
                    {% if saida %} 
                        <div class="form-group col-2">
                            <label for="tipo_pagamento">Tipo Pagamento <span style="color: red;">*</span></label>
                            {{ form_parking.tipo_pagamento(id="tipo_pagamento", class="form-control" ) }}
                        </div>

                        <div class="form-group col-2">
                            <label for="valor_recebido">Valor Recebido <span style="color: red;">*</span></label>
                            {{ form_parking.valor_recebido(id="valor_recebido", class="form-control", placeholder="", value="0") }}
                        </div>
                        
                        <div class="form-group col-2">
                            <label for="desconto">Desconto</label>
                            {{ form_parking.desconto(id="desconto", class="form-control", placeholder="", value="0" ) }}
                        </div>

                        <div class="form-group col-2">
                            <label for="troco">Troco</label>
                            {{ form_parking.troco(id="troco", class="form-control", placeholder="", value="0", readonly=True) }}
                        </div>

                        <div class="form-group col-2">
                            <label for="valor_liquido">Valor Líquido</label>
                            {{ form_parking.valor_liquido(id="valor_liquido", class="form-control", placeholder="", readonly=True, value=parking.valor_liquido_estacionamento ) }}
                        </div>

                        <div class="form-group col-2">
                            <label for="valor_total">Valor Total</label>
                            {{ form_parking.valor_total(id="valor_total", class="form-control", placeholder="", readonly=True, value=parking.valor_total_estacionamento ) }}
                        </div>
                    {% endif %}
                </div>

                {% if parking.situacao_estacionamento == 'pendente' %}
                    <div class="ml-3 mt-3">
                        <button id="addService" class="btn btn-primary mr-2" type="button">Adicionar serviço</button>
                        <button id="removeService" class="btn btn-danger" type="button">Remover serviço </button>
                    </div>
                {% endif %}
                
                <div class="table-responsive col-12">
                    <table id="serviceParking" name="services" class="table table-striped table-bordered">
                        <thead class="thead-default bg-white">
                            <tr>
                                <th>Serviço</th>
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Preço</th>
                                <th>Tipo</th>
                                <th>Origem</th>
                                <th>Excluido</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% set valueHour = 0 %}
                            {% for service in services %}
                                <tr>
                                    <td>{{ service.id_servico }}</td>
                                    <td>{{ service.nome_servico }}</td>
                                    <td>{{ service.descricao_servico }}</td>
                                    <td>{{ service.preco_servico }}</td>
                                    <td>{{ service.tipo_servico.capitalize() }}</td>
                                    <td>{{ service.id_servico }}</td>
                                    <td>false</td>
                                </tr>
                                {% if service.tipo_servico.lower() == 'estacionamento' %}
                                    {{ form_parking.servicos(id="valor_hora", value=service.preco_servico) }}
                                {% endif %}
                            {% endfor %}
                        </tbody>
    
                    </table>
                </div>

                {{ form_parking.servicos(id="services") }}
                {{ form_parking.situacao(id="situacao", value=parking.situacao_estacionamento, type="hidden") }}
                
                <div class="text-center mt-4">
                    {% if parking.situacao_estacionamento == 'pendente' %}
                        <button id="buttonSubmit" class="btn btn-primary mr-4" type="submit">Salvar</button>
                        <a class="btn btn-danger" href="/lista-registros-estacionamento/entradas">Voltar</a>
                    {% else %}
                        <a class="btn btn-danger" href="/lista-registros-estacionamento/saidas">Voltar</a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    
    {% if saida %}
        <script>
            setTimerExit();
            calcExit();
        </script>
    {% else %}
        {% if parking.situacao_estacionamento == 'pendente' %}
            <script>
                setTimerEntry();
                $(document).ready(function() {
                    $('#placa_veiculo').select2();
                    $('#id_vaga').select2();
                });
            </script>
        {% endif %}
    {% endif %}


{% endblock %}

app/templates/parking/parking_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-flex justify-content-center mt-3 col-xs-12 col-sm-10">
        <div class="col-sm-10 col-xs-12">
            {% if 'entradas' in request.path %}
                <h2 class="mb-3">Lista de Entradas</h2>
            {% else %}
                <h2 class="mb-3">Lista de Saídas</h2>
            {% endif %}
            
            <div class="table-responsive">
                <table id="table" class="table table-striped table-bordered">
                    <thead class="thead-default bg-white">
                        <tr>
                            <th>Id</th>
                            <th>Placa</th>
                            <th>Entrada</th>
                            <th>Saída</th>
                            <th>Observação</th>
                            <th>Total Servicos</th>
                            <th>Situação</th>
                            <th class="text-center">Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for park in parkings %}
                            <tr>
                                <td>{{ park.id_estacionamento }}</td>
                                <td>{{ park.veiculo_placa_veiculo }}</td>
                                <td>{{ park.entrada_estacionamento }}</td>
                                <td></td>
                                <td>{{ park.observacao_estacionamento }}</td>
                                <td>{{ park.valor_total_estacionamento }}</td>
                                <td>{{ park.situacao_estacionamento.capitalize() }}</td>
                                
                                <td class="d-flex justify-content-center">
                                    {% set disable = 'pointer-events: none' %}
                                    {% if park.situacao_estacionamento == 'pendente' %}
                                        <a class="btn btn-success" href="{{ url_for('parking.exit_parking', id_estacionamento=park.id_estacionamento) }}">Registrar Saída</a>
                                        <div class="ml-3"></div>
                                        <a class="btn btn-primary" href="{{ url_for('parking.edit_parking', id_estacionamento=park.id_estacionamento) }}">Editar</a>
                                        <div class="ml-3"></div>
                                    {% else %}
                                        <a class="btn btn-primary" href="{{ url_for('parking.edit_parking', id_estacionamento=park.id_estacionamento) }}">Visualizar</a>
                                        <div class="ml-3"></div>
                                    {% endif %}
                                    <button class="btn btn-danger" onclick="excluir( '{{ park.id_estacionamento }}' )">Excluir</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>

    </div>

    <!-- Função para confirmar exclusão -->
    <script>
        function excluir(id_estacionamento) {
            if (confirm('Deseja excluir o registro ' + id_estacionamento + '?')) {
                window.location.href = '/excluir-registro-estacionamento/' + id_estacionamento
            }
        }
    </script>

{% endblock %}

app/templates/parking/parking_register.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table-service.css') }}">

    <div class="d-flex justify-content-center mt-3 p-sm-2 col-xs-12 col-sm-10">
        <div class="col-sm-12 col-xs-12">
            <h2 class="p-3 mb-3">Registrar Entrada</h2>

            <form method="POST">
                {{ form_parking.csrf_token }}

                <div class="d-flex justify-content-center">
                    <div class="form-group col-4">
                        <label for="placa_veiculo">Placa do Veículo <span style="color: red;">*</span></label>
                        {{ form_parking.placa_veiculo(id="placa_veiculo", class="form-control", placeholder="Digite a placa do veículo", readonly=read_only) }}
                    </div>

                    <div class="form-group col-2">
                        <label for="id_vaga">Vaga <span style="color: red;">*</span></label>
                        {{ form_parking.id_vaga(id="id_vaga", class="form-control", placeholder="Digite a vaga", readonly=read_only) }}
                    </div>

                    <div class="form-group col-2">
                        <label for="vaga_disponivel">Vagas Disponíveis</label>
                        {{ form_parking.vaga_disponivel(id="vaga_disponivel", class="form-control", readonly=True, value=qtdVacancy) }}
                    </div>

                    <div class="form-group col-4">
                        <label for="observacao">Observação</label>
                        {{ form_parking.observacao(id="observacao", class="form-control", placeholder="Digite uma observação") }}
                    </div>
                </div>
                
                <div class="d-flex justify-content-center">
                    <div class="form-group col-4">
                        <label for="entrada">Data/hora Entrada</label>
                        {{ form_parking.entrada(id="entrada", class="form-control", placeholder="", readonly=True ) }}
                    </div>

                    <div class="form-group col-4">
                        <label for="situacao">Situação Pagamento</label>
                        {{ form_parking.saida(id="situacao", class="form-control", placeholder="", readonly=True, value='Pendente' ) }}
                    </div>

                    <div class="form-group col-4">
                        <label for="valor_total">Valor Total Serviços</label>
                        {{ form_parking.valor_total(id="valor_total", class="form-control", placeholder="", value=0, readonly=True ) }}
                    </div>
                </div>

                <div class="ml-3 mt-3">
                    <button id="addService" class="btn btn-primary mr-2" type="button">Adicionar serviço</button>
                    <button id="removeService" class="btn btn-danger" type="button">Remover serviço</button>
                </div>
                
                <div class="table-responsive col-12">
                    <table id="serviceParking" name="services" class="table table-striped table-bordered">
                        <thead class="thead-default bg-white">
                            <tr>
                                <th>Serviço</th>
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Preço</th>
                                <th>Tipo</th>
                                <th>Origem</th>
                                <th>Excluido</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>0</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
    
                    </table>
                </div>

                {{ form_parking.servicos(id="services") }}

                <div class="text-center mt-4">
                    <button id="buttonSubmit" class="btn btn-primary mr-4" type="submit">Salvar</button>
                    <a class="btn btn-danger" href="/lista-registros-estacionamento/entradas">Voltar</a>
                </div>
            </form>
        </div>
    </div>

    <script>
        setTimerEntry();
        $(document).ready(function() {
            $('#placa_veiculo').select2();
            $('#id_vaga').select2();
        });
    </script>

{% endblock %}